[project]
name = "apicallmaster"
version = "0.1.0"
description = "uv dependencies"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.57.1",
    "chromadb>=1.1.0",
    "duckdb>=1.4.0",
    "google-genai>=1.24.0",
    "groq>=0.29.0",
    "openai>=1.91.0",
    "pandas>=2.3.0",
    "pyarrow>=20.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "sentence-transformers>=5.1.1",
    "streamlit>=1.46.0",
    "neo4j>=5.22.0",
    "browser-use>=0.5.5",
    "playwright>=1.52.0",
    "patchright>=1.52.5",
]
